# -*- coding: utf-8 -*-
"""Decision tree for classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRmnUjUYJ9ZMJ-YM1rO3P1v7QpdwpWHR
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import accuracy_score
import matplotlib. pyplot as plt

data =pd.read_csv("/content/iris.csv")

X= data.drop("Species",axis=1)
Y= data["Species"]

X_main,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

model=DecisionTreeClassifier(random_state=42)
model.fit(X_main,Y_train)

Y_pred=model.predict(X_test)

accuracy=accuracy_score(Y_test,Y_pred)
print("Accuracy:",accuracy)

plt.figure(figsize=(12,8))
plot_tree(model,feature_names=X.columns,class_names=model.classes_,filled=True)
plt.show()